### ISSUE TITLE
Module Resolution Error in v5.0.0

### ISSUE THREAD

**Issue by SamWanekeya** [drcallaway/apollo-link-timeout#75]
**Issue Summary**

When upgrading to apollo-link-timeout v5.0.0, I encountered a compilation error related to module resolution. The issue appears to be that timeoutLink.js is trying to import ./TimeoutError without specifying the .js extension, which causes Webpack to fail due to strict ES module resolution.

**Error Output**

    ERROR in ./node_modules/apollo-link-timeout/lib/esm/timeoutLink.js 25:0-42
    Module not found: Error: Can't resolve './TimeoutError' in 'projectname\node_modules\apollo-link-timeout\lib\esm'
    Did you mean 'TimeoutError.js'?
    BREAKING CHANGE: The request './TimeoutError' failed to resolve only because it was resolved as fully specified
    (probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
    The extension in the request is mandatory for it to be fully specified.
    Add the extension to the request.

**Steps to Reproduce**

1. Install apollo-link-timeout v5.0.0 using npm or yarn.
 
       npm install apollo-link-timeout@5.0.0
   
2. Import and use ApolloLinkTimeout in a React project with Webpack.
 
3. Attempt to compile the project. 

**Expected Behavior**

The package should compile without any module resolution errors.

**Actual Behavior**

Webpack throws an error indicating that ./TimeoutError cannot be resolved.

**Possible Cause**

The new version (v5.0.0) introduced separate CJS and ESM builds. However, timeoutLink.js imports ./TimeoutError without specifying .js, which is required under strict ES module resolution.

**Suggested Fix**

Explicitly specify the .js extension in timeoutLink.js:

import { TimeoutError } from "./TimeoutError.js";

This should ensure compatibility with modern ES module resolution rules.

**Environment**

    apollo-link-timeout: v5.0.0

    React: 19.0.0

    Webpack: 5.98.0

    Node.js: v23.10.0

Would love to hear if anyone else is experiencing this issue and whether a patch or workaround is planned. Thanks for the great work on this package!

**Comment by MasterOdin** [comment]
Thanks for the report, this should have been fixed in the 5.0.1 release.

**Comment by SamWanekeya** [comment]
Still not fixed, I've run some tests on the changes and I'm currently getting the error "Module not installed"

**Comment by MasterOdin** [comment]
Sorry about that! Bad publish for 5.0.1. We've published 5.0.2 which should properly fix things.
